DYC(FinalYr)/Models/AddComplainInDatabaseTable.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DYC_FinalYr_.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class AddComplainInDatabaseTable
    {
        public int Id { get; set; }
        public string ComplainCataegory { get; set; }
        public string ComplainArea { get; set; }
        public string RoadNumber { get; set; }
        public string ComplainDeatils { get; set; }
        public string Photo { get; set; }
        public string ComplainerName { get; set; }
        public string ContractNumber { get; set; }
        public string Email { get; set; }
    }
}

DYC(FinalYr)/Controllers/ComplainController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Data;
using System.Data.SqlClient;
using System.ComponentModel.DataAnnotations;
using System.IO;
using System.Web.Mvc;
using DYC_FinalYr_.Models;
namespace DYC_FinalYr_.Controllers
{
    public class ComplainController : Controller
    {
        //
        // GET: /Complain/
        public ActionResult Index()
        {
            return View();
        }

        Database1Entities db = new Database1Entities();
        public ActionResult ComplainList()
        {
            return View(db.AddComplainInDatabaseTables.ToList());
        }

        public ActionResult AddNewComplain()
        {

            var list = new List<string> { "Main Hall Missing", "Draingae", "Road Damage", "Dustbin Problem" };
            ViewBag.list = list;
            var ComplainArea = new List<string> { "Mohammadpur", "MirPur-1", "Dhamondli" };
            ViewBag.ComplainArea = ComplainArea;

            return View();
        }
        [HttpPost]
        public ActionResult AddNewComplain(AddComplainInDatabaseTable d, HttpPostedFileBase imgfile)
        {
            var list = new List<string> { "Main Hall Missing", "Draingae", "Road Damage", "Dustbin Problem" };
            ViewBag.list = list;
            var ComplainArea = new List<string> { "Mohammadpur", "MirPur-1", "Dhamondli" };
            ViewBag.ComplainArea = ComplainArea;

           // ViewBag.list = list;


            AddComplainInDatabaseTable di = new AddComplainInDatabaseTable();
            string path = uploadimage(imgfile);
            if (ComplainIsExist(d))
            {
                ViewBag.msg = "Complain is exist";
                return View();
            }

            if (path.Equals("-1"))
            {

            }
            else
            {
                di.ComplainCataegory = d.ComplainCataegory;
                di.ComplainArea = d.ComplainArea;
                di.RoadNumber = d.RoadNumber;
                di.ComplainDeatils = d.ComplainDeatils;
                //di.Photo = path;
                di.Photo = d.Photo;
                di.ComplainerName = d.ComplainerName;
                di.ContractNumber = d.ContractNumber;
                di.Email = d.Email;
                db.AddComplainInDatabaseTables.Add(di);

                db.SaveChanges();
                ModelState.Clear();
                ViewBag.msg = "data added";
            }
         

            return View();
        }

        public string uploadimage(HttpPostedFileBase file)
        {

            Random r = new Random();

            string path = "-1";

            int random = r.Next();

            if (file != null && file.ContentLength > 0)
            {

                string extension = Path.GetExtension(file.FileName);

                if (extension.ToLower().Equals(".jpg") || extension.ToLower().Equals(".jpeg") || extension.ToLower().Equals(".png"))
                {

                    try
                    {



                        path = Path.Combine(Server.MapPath("~/Content/upload"), random + Path.GetFileName(file.FileName));

                        file.SaveAs(path);

                        path = "~/Content/upload/" + random + Path.GetFileName(file.FileName);



                        //    ViewBag.Message = "File uploaded successfully";

                    }

                    catch (Exception ex)
                    {

                        path = "-1";

                    }

                }

                else
                {

                    Response.Write("<script>alert('Only jpg ,jpeg or png formats are acceptable....'); </script>");

                }

            }



            else
            {

                Response.Write("<script>alert('Please select a file'); </script>");

                path = "-1";

            }







            return path;

        }




        public bool ComplainIsExist(AddComplainInDatabaseTable d)
        {
            //string conncetion = @"Server=DESKTOP-QREDJ0M; DATABASE=MyDataBase; Integrated Security=TRUE";
            //SqlConnection sqlConncetion = new SqlConnection(conncetion);

           // AddComplainInDatabaseTable 
           int i = db.AddComplainInDatabaseTables.Where(c => c.ComplainCataegory == d.ComplainCataegory && c.ComplainArea==d.ComplainArea && c.ComplainDeatils==d.ComplainDeatils).Count();
           //string command = "SELECT * FROM AddComplainInDatabaseTable   Where ComplainCataegory = '" +d.ComplainCataegory +"'";
           //SqlCommand sqlCommand = new SqlCommand(command);

           ////sqlConncetion.Open();
           //SqlDataAdapter sqlDataAdapater = new SqlDataAdapter(sqlCommand);
           //DataTable dataTable = new DataTable();
           //sqlDataAdapater.Fill(dataTable);

           if (i > 0)
           {
               return true;
           }

           ////sqlConncetion.Close();
           return false;

        }

      

	}
}

DYC(FinalYr)/Views/Complain/AddNewComplain.cshtml
@model DYC_FinalYr_.Models.AddComplainInDatabaseTable

<h1>@ViewBag.msg</h1>
                

@using (Html.BeginForm("AddNewComplain","Complain",FormMethod.Post,new {enctype = "multipart/form-data"})) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
       
        @*<hr />*@
        @Html.ValidationSummary(true)
        <div class="row">
            <div class="col-md-12">
                <div class="form-group">
                    @Html.LabelFor(model => model.ComplainCataegory, new {@class = "control-label col-md-2"})
                    <div class="col-md-10">
                        @Html.DropDownListFor(model => model.ComplainCataegory, new SelectList(ViewBag.list), "Select One", htmlAttributes: new {@class = "form-control"})
                        @Html.ValidationMessageFor(model => model.ComplainCataegory)
                    </div>
                </div>

                <div class="form-group">
                    @Html.LabelFor(model => model.ComplainArea, new {@class = "control-label col-md-2"})
                    <div class="col-md-10">
                        @Html.DropDownListFor(model => model.ComplainArea, new SelectList(ViewBag.ComplainArea), "Select One", htmlAttributes: new {@class = "form-control"})
                        @Html.ValidationMessageFor(model => model.ComplainArea)
                    </div>
                </div>

                <div class="form-group">
                    @Html.LabelFor(model => model.RoadNumber, new {@class = "control-label col-md-2"})
                    <div class="col-md-10">
                        @Html.TextBoxFor(model => model.RoadNumber, new {@class = "form-control"})
                        @Html.ValidationMessageFor(model => model.RoadNumber)
                    </div>
                </div>

                <div class="form-group">
                    @Html.LabelFor(model => model.ComplainDeatils, new {@class = "control-label col-md-2"})
                    <div class="col-md-10">
                        @Html.TextAreaFor(model => model.ComplainDeatils, new {@class = "form-control"})
                        @Html.ValidationMessageFor(model => model.ComplainDeatils)
                    </div>
                </div>

                <div class="form-group">
                    @Html.LabelFor(model => model.Photo, new {@class = "control-label col-md-2"})
                    <div class="col-md-10">
                        @*@Html.EditorFor(model => model.Photo,, new { @class = "form-control"*@
                        <input type="file" id="imgfile" name="imgfile" class="btn btn-info">

                        @Html.ValidationMessageFor(model => model.Photo)
                    </div>
                </div>
            </div>
            @*<div class="col-md-12">*@
            <div class="form-group">
            @Html.LabelFor(model => model.ComplainerName, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.TextBoxFor(model => model.ComplainerName, new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.ComplainerName)
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.ContractNumber, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.TextBoxFor(model => model.ContractNumber, new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.ContractNumber)
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Email, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.TextBoxFor(model => model.Email, new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.Email)
            </div>
        </div>
            @*</div>*@
            <div class="form-group">
                <div class="col-md-offset-2 col-md-10">
                    <input type="submit" value="Submit" class="btn btn-default"/>
                </div>
            </div>
        </div>
        </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

DYC(FinalYr)/Views/Complain/ComplainList.cshtml
@model IEnumerable<DYC_FinalYr_.Models.AddComplainInDatabaseTable>

@{
    ViewBag.Title = "ComplainList";
}

<h2>ComplainList</h2>

<p>
    @Html.ActionLink("Create New", "Create")
</p>
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.ComplainCataegory)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.ComplainArea)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.RoadNumber)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.ComplainDeatils)
        </th>
        <th>
          @Html.DisplayNameFor(model => model.Photo)
            
        </th>
        <th>
            @Html.DisplayNameFor(model => model.ComplainerName)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.ContractNumber)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Email)
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.ComplainCataegory)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.ComplainArea)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.RoadNumber)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.ComplainDeatils)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Photo)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.ComplainerName)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.ContractNumber)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Email)
        </td>
        <td>
            @Html.ActionLink("Edit", "Edit", new { id=item.Id }) |
            @Html.ActionLink("Details", "Details", new { id=item.Id }) |
            @Html.ActionLink("Delete", "Delete", new { id=item.Id })
        </td>
    </tr>
}

</table>

DYC(FinalYr)/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")

</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Application name", "Index", "Home", null, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Home", "Index", "Home")</li>
                    <li>@Html.ActionLink("About", "About", "Home")</li>
                    <li>@Html.ActionLink("Contact", "Contact", "Home")</li>
                </ul>
                @Html.Partial("_LoginPartial")
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - My ASP.NET Application</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>